name: 'Clang-format'

description: 'Clang-format the repository recursively to check or directly reformat your C++ project.'

inputs:
  commit:
    description: 'Directly commit applied changes.'
    required: false
    default: false
  commit-msg:
    description: 'Commit message in case changes are applied.'
    required: false
    default: 'clang'
  commit-user-name:
    description: 'Git username of the commit.'
    required: false
    default: ''
  commit-user-email:
    description: 'Git user email of the commit.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo "${{ github.action_path }}" >> $GITHUB_PATH
  - shell: bash
    run: format_clang.sh ${{ inputs.commit }} ${{ inputs.commit-msg }} ${{ inputs.commit-user-name }} ${{ inputs.commit-user-email }}
